### ISSUE TITLE
Missing source in repository

### ISSUE THREAD

**Issue by fj** [Viralmaniar/BigBountyRecon#1]
This application seems to have been deployed without source. Because an executable that is designed to uncover security holes is necessarily problematic to run without understanding how it works, the lack of available source code is both concerning and detrimental for the tool's trustworthiness.

I recommend remedying this by including the source and any necessary build instructions.

**Comment by jayateertha043** [comment]
I support this issue , without the source code we can't understand how things work in the background.
Releasing the source code may also improve support from the open source community in adding new features or fixing the existing bugs.

**Comment by Viralmaniar** [comment]
All files added.

Any run results - https://app.any.run/tasks/b31a5e6a-7ead-470e-b5e8-02fffd55f255/
